esphome:
  name: thermostat
  friendly_name: Thermostat

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_GENERATED_API_KEY_GOES_HERE"

ota:
  - platform: esphome
    password: "YOUR_GENERATED_OTA_PASSWORD_GOES_HERE"

# I have not tested Ethernet comms, but these 
# values are appropriate for this board. 
# Uncomment below to try Ethernet:
#  type: JL1101
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO17_OUT
#  phy_addr: 0
#  power_pin: GPIO0
  # Optional manual IP
  # manual_ip:
  #  static_ip: 192.168.1.99
  #  gateway: 192.168.1.1
  #  subnet: 255.255.0.0


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Thermostat Fallback Hotspot"
    password: ""

captive_portal:
    
status_led:
  pin: GPIO15

binary_sensor:
  # If the API connection to home assistant is interrupted then we revert to 
  # using the local temp sensor
  - platform: status
    name: "Thermostat Status"
    id: statussensor

  - platform: gpio
    pin:
      number: GPIO36
      inverted: True
      mode:
        input: true
    name: "INPUT1"
    disabled_by_default: True

  - platform: gpio
    pin:
      number: GPIO39
      inverted: True
      mode:
        input: true
    name: "INPUT2"
    disabled_by_default: True

  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
      mode:
        input: true
    name: "INPUT3" 
    disabled_by_default: True

  - platform: gpio
    pin:
      number: GPIO35
      inverted: True
      mode:
        input: true
    name: "INPUT4"
    disabled_by_default: True

sensor:
  - platform: dht
    pin: GPIO5
    model: DHT22
    temperature:
      name: "Local Temperature"
      id: local_temperature
      accuracy_decimals: 2
      filters:
        - lambda: return (x * 9.0 / 5.0) + 32;
      device_class: temperature
      state_class: measurement
      unit_of_measurement: °F     
    humidity:
      name: "Local Humidity"
      id: local_humidity
      accuracy_decimals: 1
      device_class: humidity
      state_class: measurement
    update_interval: 10s
    
  - platform: homeassistant
    name: "House Average Temperature"
    entity_id: sensor.house_average_temp
    internal: true
    id: average_temperature
    filters:
        - lambda: return (x - 32.0) * 5.0 / 9.0;
    accuracy_decimals: 2
    device_class: temperature
    unit_of_measurement: "°C"

  - platform: homeassistant
    name: "House Average Humidity"
    entity_id: sensor.house_average_humidity
    internal: true
    id: house_average_humidity
    accuracy_decimals: 1
    device_class: humidity
    unit_of_measurement: "%"

  - platform: template
    name: Measured Temperature
    id: measured_temperature
    #internal: True
    lambda: |-
      if (id(statussensor).state) {
        return id(average_temperature).state;
      } else {
        return id(local_temperature).raw_state;
      }
    update_interval: 10s
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"

  - platform: template
    name: Measured Humidity
    id: measured_humidity
    #internal: True
    lambda: |-
      if (id(statussensor).state) {
        return id(house_average_humidity).state;
      } else {
        return id(local_humidity).state;
      }
    update_interval: 10s
    accuracy_decimals: 1
    device_class: humidity
    state_class: measurement
    unit_of_measurement: "%"

switch:
  - platform: gpio
    pin: GPIO16
    id: G
    name: "Fan Relay"
    disabled_by_default: True
    restore_mode: ALWAYS_OFF
    on_turn_off: 
      then:
        - switch.turn_off: W1
        - switch.turn_off: W2
        - switch.turn_off: Y
        
  - platform: gpio
    pin: GPIO02
    id: W1
    name: "Heat Relay"
    disabled_by_default: True
    restore_mode: ALWAYS_OFF
    interlock: [Y]
    on_turn_on: 
      then:
        - switch.turn_on: G
        - switch.turn_off: Y
        
  - platform: gpio
    pin: GPIO32
    id: W2
    name: "Supplemental Heat Relay"
    disabled_by_default: True
    restore_mode: ALWAYS_OFF
    interlock: [Y]
    on_turn_on: 
      then:
        - switch.turn_on: G
        - switch.turn_off: Y

  - platform: gpio
    pin: GPIO12
    id: Y
    name: "Cool Relay"
    disabled_by_default: True
    restore_mode: ALWAYS_OFF
    interlock: [W1, W2]
    on_turn_on: 
      then:
        - switch.turn_on: G 
        - switch.turn_off: W1     
        - switch.turn_off: W2   

# Dual-point Climate Controller
climate:
  - platform: thermostat
    visual:
      min_temperature: 55 °F
      max_temperature: 95 °F
      temperature_step: 0.5 °F
      min_humidity: 30%
      max_humidity: 99%
    name: "HVAC Controller"
    id: hvac_controller
    sensor: measured_temperature
    humidity_sensor: measured_humidity
    cool_deadband: 0.5 °F
    cool_overrun:  0.5 °F
    heat_deadband: 0.5 °F
    heat_overrun:  0.5 °F
    fan_with_cooling: True
    fan_with_heating: True
    min_cooling_off_time: 300s
    min_cooling_run_time: 300s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_fanning_off_time: 10s
    min_fanning_run_time: 10s
    min_idle_time: 5s
    set_point_minimum_differential: 5 °F
    cool_action:
      - switch.turn_on: Y
    heat_action:
      - switch.turn_on: W1
    max_heating_run_time: 300s
    supplemental_heating_delta: 8 °F
    supplemental_heating_action: 
      - switch.turn_on: W2
    idle_action:
      - switch.turn_off: W1
      - switch.turn_off: W2
      - switch.turn_off: Y
      - delay: 3s
      - switch.turn_off: G
    fan_only_action: 
      - switch.turn_on: G
    default_preset: Home
    on_boot_restore_from: memory
    preset:
      - name: Home
        default_target_temperature_low: 63 °F
        default_target_temperature_high: 72 °F
        mode: HEAT_COOL
      - name: Comfort
        default_target_temperature_low: 65 °F
        default_target_temperature_high: 71 °F
        mode: HEAT_COOL
      - name: Sleep
        default_target_temperature_low: 62 °F
        default_target_temperature_high: 70 °F
        mode: HEAT_COOL
      - name: Away
        default_target_temperature_low: 55 °F
        default_target_temperature_high: 80 °F
        mode: HEAT_COOL
      - name: OverCool
        default_target_temperature_low: 55 °F
        default_target_temperature_high: 66 °F
        mode: COOL
      - name: BYPASS
        default_target_temperature_low: 55 °F
        default_target_temperature_high: 80 °F
        mode: "OFF"
